# Generated by Django 4.2.6 on 2023-10-27 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('tax', models.FloatField(default=0.0, max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_num', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('mfgnum', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('status', models.CharField(choices=[('Waiting_on_Assignment', 'Waiting on Assignment'), ('Checked_Out', 'Checked Out'), ('Needs_QC', 'Needs QC'), ('Parts_On_Order', 'Parts On Order'), ('QC_PASS', 'QC PASS'), ('QC_FAIL', 'QC FAIL')], default='Waiting_on_Assignment', max_length=25)),
                ('qc', models.CharField(choices=[('QC_FAIL', 'QC FAIL'), ('QC_PASS', 'QC PASS'), ('WAITING_QC', 'Waiting On QC'), ('NO_QC', '')], default='NO_QC', max_length=20)),
                ('custom_product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_product_description', models.TextField(blank=True, max_length=100, null=True)),
                ('custom_product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('workOrder_num', models.AutoField(primary_key=True, serialize=False)),
                ('workOrder_date', models.DateField()),
                ('status', models.CharField(choices=[('Waiting_on_Assignment', 'Waiting on Assignment'), ('Being_Worked_On', 'Being Worked On'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Rush', 'Rush')], default='Waiting_on_Assignment', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_rush', models.BooleanField(default=False)),
                ('return_by', models.DateField(default=None, null=True)),
                ('quote_required', models.BooleanField(default=False)),
                ('specialInstructions', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client')),
                ('items', models.ManyToManyField(blank=True, through='invoice.WorkOrderItem', to='invoice.product')),
            ],
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='workOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorders'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/signatures/')),
                ('customer_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorders')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.producttype'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(default='', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, through='invoice.InvoiceItem', to='invoice.product'),
        ),
        migrations.CreateModel(
            name='CompanyRepSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyRep', models.ImageField(upload_to='static/img/signatures/')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorders')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Primary', 'primary'), ('WorkOrder', 'WorkOrder'), ('Normal', 'Normal')], default='Normal', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.client')),
            ],
        ),
    ]
