# Generated by Django 4.2.5 on 2023-11-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorders',
            name='account_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.clientcontact'),
        ),
    ]
